#!/bin/bash -eu

source ./utils/include

[ "${UID?}" -ne 0 ] && { log "run as root." ; exit 1; }

MODE="${1:-"arch-i3"}"

case "${MODE}" in
	"arch-i3")
		arch::install
		i3::install
	;;
esac

exit $?
